name: Update WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          IGNORED_LANGUAGES: HTML CSS TOML
          
